import Head from "next/head";
import styles from "../styles/Home.module.css";
import {css} from "@emotion/css";
import {useColorMode} from "theme-ui";
import NavBar from "./Navbar";
import ToggleSwitch from "./Toggle";
import Link from "next/link";

const test = css`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background: ${"var(--theme-ui-colors-primary)"};
`;

 function Home() {
  const [colorMode, setColorMode] = useColorMode();
  return (
    <>
      
      <div >
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>


      <main className={test}>
        
      </main>
    </div>

      <section className={test}>
      <Link href={"/Sidebar_left"}>Sidebar test</Link>
        <h1 className={styles.title}>
          Welcome to Next
        </h1>
        <button
          onClick={(e) => {
            setColorMode(colorMode === "default" ? "dark" : "default");
          }}
        >
          Toggle {colorMode === "default" ? "Dark" : "Light"}
        </button>
      </section>

      </div>
      </>

  );
}

export default Home