import Head from "next/head";
import {css} from "@emotion/css";
import {useColorMode} from "theme-ui";
const test = css`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background: ${"var(--theme-ui-colors-primary)"};
`;

const container = css`
  padding: 0 2rem;
`;

export default function Home() {
  const [colorMode, setColorMode] = useColorMode();
  return (
    <div className={container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={test}>
        <button
          onClick={(e) => {
            setColorMode(colorMode === "default" ? "dark" : "default");
          }}
        >
          Toggle {colorMode === "default" ? "Dark" : "Light"}
        </button>
      </main>
    </div>
  );
}
